### ISSUE TITLE
How is this different from https://github.com/googlemaps/ios-places-sdk

### ISSUE THREAD

**Issue by akshaaatt** [googlemaps/ios-places-swift-sdk#3]
Which one should I be using if I want to use the Places SDK (New) ?

**Comment by viere1234** [comment]
It's just a different interface. But the GooglePlacesSwift can only work with Places API (New).
Since you want to use Places API (New), both Google Places SDK and Google Places Swift SDK will work for you.

**Comment by marchy** [comment]
Can you please drop [release notes](https://github.com/googlemaps/ios-places-swift-sdk/releases) on what changed for version 0.2.0?

I don't see anything mentioned in the GitHub releases (where it should always be) nor on the [Version page](https://developers.google.com/maps/documentation/places/ios-sdk/versions) in the docs (only mentions the 9.X.X releases)

**Comment by wangela** [comment]
Please see [this blog post](https://mapsplatform.google.com/resources/blog/new-sdks-from-google-maps-platform-support-more-type-safe-and-simpler-swift/) announcing the Places Swift SDK for iOS and a comparison table comparing this SDK with the Places SDK for iOS.

**Comment by wangela** [comment]
@marchy I am closing this issue about the differences between the Places Swift SDK and Places SDK, and have opened #16 to capture the challenges with finding the release notes for this SDK. Please follow that.
